<?php
/*********************************************************************************
 * "Powered by BizForce"
 * BFtool new_Fields_types 1.0 2021-01-28
 *  
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN BF_Dynamicbases
 */


class BF_Dynamicbases_sugar extends Basic {
    var $new_schema = true;
    var $module_dir = 'BF_Dynamicbases';
    var $object_name = 'BF_Dynamicbases';
    var $table_name = 'bf_dynamicbases';
    var $importable = true;
    var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
    var $id;
    var $name;
    var $date_entered;
    var $date_modified;
    var $modified_user_id;
    var $modified_by_name;
    var $created_by;
    var $created_by_name;
    var $description;
    var $deleted;
    var $created_by_link;
    var $modified_user_link;
    var $assigned_user_id;
    var $assigned_user_name;
    var $assigned_user_link;
    var $name_of_module;
    var $is_first;
    public function __construct() {
            parent::__construct();
    }
    function bean_implements($interface){
        switch($interface){
                case 'ACL': return false;
        }
        return false;
    }

		
}
?>